from setuptools import setup, find_packages


setup(
    name='church_encoding',
    version='0.1.1',
    license='BSD',
    author='Risto Stevcev',
    author_email='risto1@gmail.com',
    url='http://github.com/Risto-Stevcev/python-church-encodings',
    description='Church encodings written in Python',
    long_description=open('README.md','r').read(),
    packages=find_packages(),
    keywords = 'church encoding encodings',
    test_suite = 'church_encoding.test',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.3',
        'Programming Language :: Python :: 2.4',
        'Programming Language :: Python :: 2.5',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.0',
        'Programming Language :: Python :: 3.1',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Mathematics'
         ],
)
